#!/usr/bin/env python3

import json
import os

import yaml


def get_file_size(file_path: str) -> int:
    return os.path.getsize(file_path)


def generate_index(directory: str, output_file: str, base_url: str) -> None:
    index = {
        "type": "dir",
        "size": 0,
        "name": directory,
        "path": directory,
        "download_url": f"{base_url}/{output_file}",
        "_links": {
            "self": f"{base_url}/{output_file}",
        },
        "entries": [],
    }

    for root, _dirs, files in os.walk(directory):
        for file in files:
            if file.endswith(".yaml"):
                file_path = os.path.join(root, file)
                relative_path = file_path.replace("\\", "/")
                with open(file_path) as f:
                    instrument = yaml.safe_load(f)
                    file_info = {
                        "type": "file",
                        "size": get_file_size(file_path),
                        "name": file,
                        "path": relative_path,
                        "urn": instrument["urn"],
                        "download_url": f"{base_url}/{relative_path}",
                        "_links": {
                            "self": f"{base_url}/{relative_path}",
                        },
                    }
                    index["entries"].append(file_info)

    with open(output_file, "w") as f:
        json.dump(index, f, indent=4)


BASE_URL = "https://minbzk.github.io/instrument-registry"
DIRECTORY = "instruments"
OUTPUT_FILE = "index.json"

generate_index(DIRECTORY, OUTPUT_FILE, BASE_URL)
print(f"Generated {OUTPUT_FILE}")
