name: sync-schedule
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PIPX_BIN_DIR: /usr/local/bin
  PYTHON_VERSION: "3.12"

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      file_size: ${{ steps.sync.outputs.file_size }}
      file_contents: ${{ steps.sync.outputs.file_contents }}
      sync_exit_code: ${{ steps.sync.outputs.sync_exit_code }}
    steps:
      - uses: actions/checkout@v5

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Run Sync script
        id: sync
        continue-on-error: true
        run: |
          script/sync --verbose false > diff.txt
          echo "sync_exit_code=$?" >> $GITHUB_OUTPUT
          file_size=$(stat -c%s diff.txt)
          echo "file_size=$file_size" >> $GITHUB_OUTPUT
          {
            echo "file_contents<<EOF"
            cat diff.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  notifyMattermost:
    runs-on: ubuntu-latest
    needs: [sync]
    if: ${{ needs.sync.outputs.file_size != '0' && needs.sync.outputs.sync_exit_code != '0' }}
    steps:
      - name: Send notify
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_DEV }}
          TEXT: |
            Wijziging geconstateerd in bestanden van het Algoritmekader die invloed hebben op het Task Registry.
            [Link naar de GitHub Action run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ```
            ${{ needs.sync.outputs.file_contents }}
            ```
          MATTERMOST_USERNAME: ${{ github.triggering_actor }}
